#!/bin/sh

set -e

cp -a tests $ADTTMP/tests
cd $ADTTMP/tests

for python in "$@"; do
    echo "Running “$python ./runtests.py --verbosity 2”"
    LC_ALL=C.UTF-8 $python ./runtests.py --verbosity 2
done
